### ISSUE TITLE
Liferay Portal 7.3.0 ga1 REST Builder Issue With Dependency 

### ISSUE THREAD

**Issue by Mayursinh43** [martin-dominguez/dev24restbuilder#1]
Hi Martin ,

i have tried to implement this in 7.3.0 ga1 but having a dependency issue. please check the below code.

Restbuilder-impl build.gradle File.

buildscript {
    dependencies {
        classpath group: "com.liferay", name: "com.liferay.gradle.plugins.rest.builder", version: "1.0.114"
    }

    repositories {
        maven {
            url "https://repository-cdn.liferay.com/nexus/content/groups/public"
        }
    }
}

apply plugin: "com.liferay.portal.tools.rest.builder"

dependencies {
	compileOnly group: "org.osgi", name: "org.osgi.core"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations"
	compileOnly group: "com.liferay.portal", name: "release.portal.api", version: "7.3.0-ga1"
	compileOnly project(":modules:RestBuilder-api")
}

I am able to Restbuild successfully . after adding  "compileOnly group: "com.liferay.portal", name: "release.portal.api", version: "7.3.0-ga1"   this, still i have many things as not resolve . check below sceenshot.
![Capture](https://user-images.githubusercontent.com/15194015/94442528-b3b17700-01c1-11eb-91c5-24d815ec5e4a.PNG)

**Comment by martin-dominguez** [comment]
Hi @Mayursinh43,
before start check a couple of points:

- Check that your build.gradle file in the API module is also well configured
- Check that you exported both packages in API modules in your bnd.bnd file.

But probably your problem comes because the version of the Rest Builder that you are using is newer that the version of Liferay CE... 

If you check this [matrix](https://github.com/javierdearcos/rest-builder-docs/blob/master/Version%20Matrix.md) you'll see that the version 1.0.114 requires the Vulcan API 7.6.0 and in Liferay 7.3.0 the version of Vulcan API available is 7.1.1... So, if the points above didn't solve your problems try to use a older version of the RestBuilder (1.0.93 - 1.0.95) or a newer version of Liferay (minimum 7.3 GA3).

Don't forget remove all the generated code and the OperationIds in you OpenAPI profile before run `gw buildREST` again
